[package]
name = "lagos"
description = "Generic identity-aware gateway binary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lagos-core = { path = "../lagos-core" }
anyhow.workspace = true

[lints]
workspace = true
